### ISSUE TITLE
Improve yaml validation for functions

### ISSUE THREAD

**Issue by marktani** [graphcool/graphcool-framework#309]
<a href="https://github.com/marktani"><img src="https://avatars1.githubusercontent.com/u/1780597?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [marktani](https://github.com/marktani)**
_Friday Oct 20, 2017 at 09:04 GMT_
_Originally opened as https://github.com/graphcool/prisma/issues/934_

----

![pasted image at 2017_10_19 06_15 pm](https://user-images.githubusercontent.com/1780597/31813365-57c04dfc-b586-11e7-8a4a-1525f08137e6.png)

```yml
functions:
  onResponse:
    handler:
      type: subscription
      code: src/onRequest/index.ts
      query: src/onRequest/query.graphql
```
