### ISSUE TITLE
Environment variables not passed to webhooks

### ISSUE THREAD

**Issue by marktani** [graphcool/graphcool-framework#371]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kbrandwijk](https://github.com/kbrandwijk)**
_Monday Nov 06, 2017 at 04:22 GMT_
_Originally opened as https://github.com/graphcool/prisma/issues/1170_

----

**Current behavior**
When I define an environment variable for a function in my service definition, that variable is available in `process.env` for inline functions. However, these variables are not passed to webhooks.

**Reproduction**
```yaml
functions:
  hello:
    handler:
      webhook:
        url: http://localhost:4000/hello
    type: resolver
    schema: src/hello.graphql
    environment:
      var1: value
```

**Expected behavior?**
In the original feature request for environment variable support, I proposed adding them to the context of the function. This would work for webhooks. They should be part of the request object.
