### ISSUE TITLE
'No valid session' error when deploying with automate ci

### ISSUE THREAD

**Issue by marktani** [graphcool/graphcool-framework#386]
<a href="https://github.com/chinclubi"><img src="https://avatars3.githubusercontent.com/u/5950717?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [chinclubi](https://github.com/chinclubi)**
_Thursday Nov 09, 2017 at 06:42 GMT_
_Originally opened as https://github.com/graphcool/prisma/issues/1225_

----

**Current behavior**
- I try to deploy my graphcool project with gitlab-ci
- Here is my simple `.gitlab-ci.yml` file
```
stages:
- build

build: 
  stage: build
  only:
    - master
  script:
    - yarn
    - yarn build
    - graphcool login -T \"${GRAPHCOOL_TOKEN}\"
    - graphcool deploy -t test --force
```
- Push my last commit to `master` branch.
- Finally, I receive this error
![screen shot 2560-11-08 at 8 42 28 pm](https://user-images.githubusercontent.com/5950717/32588440-3cebb636-c541-11e7-8c1a-e253d44cd37a.png)

**Reproduction**
1. create graphcool project with `graphcool init`
2. create a simple `.graphcoolrc`
```
targets:
  dev: shared-ap-northeast-1/{{your-gl-project-id}}
  default: dev
clusters:
  default: shared-ap--1
```
3. create a `.gitlab-ci.yml`
```
image: node:6
before_script:
- npm install -g graphcool
stages:
  - deploy
deploy:
  stage: deploy
  script:
    - graphcool login -T \"${GRAPHCOOL_TOKEN}\"
    - graphcool deploy -t test --force
```
4. set `GRAPHCOOL_TOKEN` variable with your graphcool token >> [gitlab ci docs](https://docs.gitlab.com/ee/ci/variables/#secret-variables)
5. commit&push your code to `master` branch

**Comment by marktani** [comment]
<a href="https://github.com/kbrandwijk"><img src="https://avatars1.githubusercontent.com/u/852069?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kbrandwijk](https://github.com/kbrandwijk)**
_Thursday Nov 09, 2017 at 10:06 GMT_

----

You should skip `graphcool login`. When setting the env var `GRAPHCOOL_TOKEN`, you can call `graphcool deploy` directly.

**Comment by marktani** [comment]
<a href="https://github.com/chinclubi"><img src="https://avatars3.githubusercontent.com/u/5950717?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [chinclubi](https://github.com/chinclubi)**
_Wednesday Nov 15, 2017 at 17:58 GMT_

----

@kbrandwijk 
According to #626, I have updated `.gitlab-ci.yml` and set the env var `GRAPHCOOL_TARGET`. 
```
image: node:6
before_script:
- npm install -g graphcool
stages:
  - deploy
deploy:
  stage: deploy
  script:
    - graphcool deploy
```
I still got an error:
![image](https://user-images.githubusercontent.com/5950717/32851959-16b1bd6c-ca69-11e7-9804-7f3abfbc3995.png)

**Comment by marktani** [comment]
<a href="https://github.com/nguansak"><img src="https://avatars0.githubusercontent.com/u/1378448?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [nguansak](https://github.com/nguansak)**
_Sunday Nov 26, 2017 at 18:04 GMT_

----

I also try build ~/.graphcoolrc file with following script
```
image: node:6
before_script:
- npm install -g graphcool
stages:
  - deploy
deploy:
  stage: deploy
  script:
    - echo \"platformToken: ${GRAPHCOOL_TOKEN}\" > ~/.graphcoolrc
    - graphcool deploy -t test --force
```
but Gitlab CI Lint throw the error
**Status**: syntax is incorrect 
**Error**: jobs:deploy:script config should be a string or an array of strings

BTW, I able to work around by using

```
- cp .graphcoolrc_global ~/.graphcoolrc
```

// .graphcoolrc_global

```
platformToken: >-
 <<YOUR_GRAPHCOOL_TOKEN>>
```

but not practical because you have to put the token into a file
