### ISSUE TITLE
opt:target not working when deploying to default target

### ISSUE THREAD

**Issue by marktani** [graphcool/graphcool-framework#399]
<a href="https://github.com/seb-z"><img src="https://avatars2.githubusercontent.com/u/33643230?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [seb-z](https://github.com/seb-z)**
_Tuesday Nov 14, 2017 at 00:57 GMT_
_Originally opened as https://github.com/graphcool/prisma/issues/1268_

----

**Current behavior**

Trying to deploy to the default target triggers errors when `${opt:target}` is used in **graphcool.yml**

Running `graphcool deploy` fails with errors like:

`A valid option to satisfy the declaration 'opt:target' could not be found.`

The workaround for now is to explicitly set the target: `graphcool deploy --target dev`

**Reproduction**

This happens given a **graphcool.yml** similar to this:

```
custom:
  dev:
    AUTH0_DOMAIN: "XXXX"
    AUTH0_API_IDENTIFIER: "XXXX"
  prod:
    AUTH0_DOMAIN: "XXXX"
    AUTH0_API_IDENTIFIER: "XXXX"


types: ./types.graphql


functions: 
  authenticate:
    handler:
      code:
        src: ./src/auth0/auth0Authentication.js
        environment:
          AUTH0_DOMAIN: ${self:custom.${opt:target}.AUTH0_DOMAIN}
          AUTH0_API_IDENTIFIER: ${self:custom.${opt:target}.AUTH0_API_IDENTIFIER}
    type: resolver
    schema: ./src/auth0/auth0Authentication.graphql
```

**Expected behavior?**

I would expect for the default target to be used as the **opt:target** value.
