### ISSUE TITLE
Model type creation without input parameters results in an 'insufficient permissions' error

### ISSUE THREAD

**Issue by marktani** [graphcool/graphcool-framework#448]
<a href="https://github.com/martijnvdbrug"><img src="https://avatars1.githubusercontent.com/u/6604455?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [martijnvdbrug](https://github.com/martijnvdbrug)**
_Friday Jan 05, 2018 at 09:42 GMT_
_Originally opened as https://github.com/graphcool/prisma/issues/1511_

----

## Current behavior
Creating a new model type without input scalar fields always returns 'insufficient permissions' error.

## Reproduction
Create a graphcool service with the following model and permissions:

**graphcool.yml**
```
types: ./types.graphql

permissions:

  # TEST
  - operation: Test.read
    authenticated: false
    query: testExists.graphql

  - operation: Test.create
    authenticated: false
    query: testExists.graphql

  - operation: Test.update
    authenticated: false

  - operation: Test.delete
    authenticated: false

rootTokens:
  - gateway
````

**types.graphql**
```
type Test @model {

    id: ID! @isUnique
    createdAt: DateTime!
    updatedAt: DateTime!

    name: String
}
```

**testExists.graphql**
```
query test {
  SomeTestExists
}
```

**Executing the following query results in 'insufficient permissions':**

```
mutation{
  createTest{
    name
  }
}
```

**Executing this query successfully creates a Test type:**

```
mutation{
  createTest(name:"test"){
    name
  }
}
```

## Expected behavior?
Both queries should result in a model type Test being created.
